# Generated by Django 4.2.11 on 2026-04-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='trouser_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
